// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Shop.Infrastructure.Data;

#nullable disable

namespace Shop.Infrastructure.Migrations
{
    [DbContext(typeof(ShopDbContext))]
    [Migration("20250630122943_AddHinhAnhSanPhamTable")]
    partial class AddHinhAnhSanPhamTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SanPhamSua", b =>
                {
                    b.Property<int>("MaSua")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaSua"));

                    b.Property<decimal?>("Gia")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("HinhAnh")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("MaLoai")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int?>("SoLuong")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenSua")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaSua")
                        .HasName("PK__SanPhamS__318B29C4E3412C4F");

                    b.HasIndex(new[] { "MaLoai" }, "IX_SanPhamSua_MaLoai");

                    b.ToTable("SanPhamSua", (string)null);
                });

            modelBuilder.Entity("Shop.Infrastructure.ChiTietDonHang", b =>
                {
                    b.Property<int>("MaCt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaCT");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaCt"));

                    b.Property<decimal?>("DonGia")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int?>("MaDh")
                        .HasColumnType("int")
                        .HasColumnName("MaDH");

                    b.Property<int?>("MaSua")
                        .HasColumnType("int");

                    b.Property<int?>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("MaCt")
                        .HasName("PK__ChiTietD__27258E74A135C457");

                    b.HasIndex(new[] { "MaDh" }, "IX_ChiTietDonHang_MaDH");

                    b.HasIndex(new[] { "MaSua" }, "IX_ChiTietDonHang_MaSua");

                    b.ToTable("ChiTietDonHang", (string)null);
                });

            modelBuilder.Entity("Shop.Infrastructure.DangKyTuVan", b =>
                {
                    b.Property<int>("MaTuVan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTuVan"));

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HoTen")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("MaKh")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayDangKy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("NoiDungTuVan")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TrangThai")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("sex")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaTuVan")
                        .HasName("PK__DangKyTu__AE2543CA7C7338C4");

                    b.HasIndex(new[] { "MaKh" }, "IX_DangKyTuVan_MaKh");

                    b.ToTable("DangKyTuVan", (string)null);
                });

            modelBuilder.Entity("Shop.Infrastructure.DanhGium", b =>
                {
                    b.Property<int>("MaDg")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaDG");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDg"));

                    b.Property<int?>("MaNd")
                        .HasColumnType("int")
                        .HasColumnName("MaND");

                    b.Property<int?>("MaSua")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayDanhGia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("NoiDung")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("Star")
                        .HasColumnType("int");

                    b.HasKey("MaDg")
                        .HasName("PK__DanhGia__27258660D39FE9C4");

                    b.HasIndex(new[] { "MaNd" }, "IX_DanhGia_MaND");

                    b.HasIndex(new[] { "MaSua" }, "IX_DanhGia_MaSua");

                    b.ToTable("DanhGia");
                });

            modelBuilder.Entity("Shop.Infrastructure.DonHang", b =>
                {
                    b.Property<int>("MaDh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaDH");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDh"));

                    b.Property<int?>("MaKh")
                        .HasColumnType("int")
                        .HasColumnName("MaKH");

                    b.Property<DateTime?>("NgayDat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<decimal?>("TongTien")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("TrangThai")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaDh")
                        .HasName("PK__DonHang__27258661DC37409C");

                    b.HasIndex(new[] { "MaKh" }, "IX_DonHang_MaKH");

                    b.ToTable("DonHang", (string)null);
                });

            modelBuilder.Entity("Shop.Infrastructure.GioHang", b =>
                {
                    b.Property<int>("MaGh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaGH");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaGh"));

                    b.Property<int?>("MaKh")
                        .HasColumnType("int")
                        .HasColumnName("MaKH");

                    b.Property<int?>("MaSua")
                        .HasColumnType("int");

                    b.Property<int?>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("MaGh")
                        .HasName("PK__GioHang__2725AE85E9FDE2C9");

                    b.HasIndex(new[] { "MaKh" }, "IX_GioHang_MaKH");

                    b.HasIndex(new[] { "MaSua" }, "IX_GioHang_MaSua");

                    b.ToTable("GioHang", (string)null);
                });

            modelBuilder.Entity("Shop.Infrastructure.HinhAnhSanPham", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DuongDan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaSanPham")
                        .HasColumnType("int");

                    b.Property<int?>("SanPhamMaSua")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SanPhamMaSua");

                    b.ToTable("HinhAnhSanPham");
                });

            modelBuilder.Entity("Shop.Infrastructure.KhachHang", b =>
                {
                    b.Property<int>("MaKh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaKH");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaKh"));

                    b.Property<string>("DiaChi")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("GioiTinh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTen")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaNd")
                        .HasColumnType("int")
                        .HasColumnName("MaND");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("MaKh")
                        .HasName("PK__KhachHan__2725CF1E8162DDA9");

                    b.HasIndex(new[] { "MaNd" }, "IX_KhachHang_MaND");

                    b.ToTable("KhachHang", (string)null);
                });

            modelBuilder.Entity("Shop.Infrastructure.LoaiSua", b =>
                {
                    b.Property<int>("MaLoai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLoai"));

                    b.Property<string>("TenLoai")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaLoai")
                        .HasName("PK__LoaiSua__730A5759DB06482B");

                    b.ToTable("LoaiSua", (string)null);
                });

            modelBuilder.Entity("Shop.Infrastructure.NguoiDung", b =>
                {
                    b.Property<int>("MaNd")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaND");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNd"));

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("VaiTro")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaNd")
                        .HasName("PK__NguoiDun__2725D724E2A90582");

                    b.ToTable("NguoiDung", (string)null);
                });

            modelBuilder.Entity("SanPhamSua", b =>
                {
                    b.HasOne("Shop.Infrastructure.LoaiSua", "MaLoaiNavigation")
                        .WithMany("SanPhamSuas")
                        .HasForeignKey("MaLoai")
                        .HasConstraintName("FK__SanPhamSu__MaLoa__403A8C7D");

                    b.Navigation("MaLoaiNavigation");
                });

            modelBuilder.Entity("Shop.Infrastructure.ChiTietDonHang", b =>
                {
                    b.HasOne("Shop.Infrastructure.DonHang", "MaDhNavigation")
                        .WithMany("ChiTietDonHangs")
                        .HasForeignKey("MaDh")
                        .HasConstraintName("FK__ChiTietDon__MaDH__46E78A0C");

                    b.HasOne("SanPhamSua", "MaSuaNavigation")
                        .WithMany("ChiTietDonHangs")
                        .HasForeignKey("MaSua")
                        .HasConstraintName("FK__ChiTietDo__MaSua__47DBAE45");

                    b.Navigation("MaDhNavigation");

                    b.Navigation("MaSuaNavigation");
                });

            modelBuilder.Entity("Shop.Infrastructure.DangKyTuVan", b =>
                {
                    b.HasOne("Shop.Infrastructure.KhachHang", "MaKhNavigation")
                        .WithMany("DangKyTuVans")
                        .HasForeignKey("MaKh");

                    b.Navigation("MaKhNavigation");
                });

            modelBuilder.Entity("Shop.Infrastructure.DanhGium", b =>
                {
                    b.HasOne("Shop.Infrastructure.NguoiDung", "MaNdNavigation")
                        .WithMany("DanhGia")
                        .HasForeignKey("MaNd")
                        .HasConstraintName("FK__DanhGia__MaND__4CA06362");

                    b.HasOne("SanPhamSua", "MaSuaNavigation")
                        .WithMany("DanhGia")
                        .HasForeignKey("MaSua")
                        .HasConstraintName("FK__DanhGia__MaSua__4D94879B");

                    b.Navigation("MaNdNavigation");

                    b.Navigation("MaSuaNavigation");
                });

            modelBuilder.Entity("Shop.Infrastructure.DonHang", b =>
                {
                    b.HasOne("Shop.Infrastructure.KhachHang", "MaKhNavigation")
                        .WithMany("DonHangs")
                        .HasForeignKey("MaKh")
                        .HasConstraintName("FK__DonHang__MaKH__440B1D61");

                    b.Navigation("MaKhNavigation");
                });

            modelBuilder.Entity("Shop.Infrastructure.GioHang", b =>
                {
                    b.HasOne("Shop.Infrastructure.KhachHang", "MaKhNavigation")
                        .WithMany("GioHangs")
                        .HasForeignKey("MaKh")
                        .HasConstraintName("FK__GioHang__MaKH__534D60F1");

                    b.HasOne("SanPhamSua", "MaSuaNavigation")
                        .WithMany("GioHangs")
                        .HasForeignKey("MaSua")
                        .HasConstraintName("FK__GioHang__MaSua__5441852A");

                    b.Navigation("MaKhNavigation");

                    b.Navigation("MaSuaNavigation");
                });

            modelBuilder.Entity("Shop.Infrastructure.HinhAnhSanPham", b =>
                {
                    b.HasOne("SanPhamSua", "SanPham")
                        .WithMany("HinhAnhSanPhams")
                        .HasForeignKey("SanPhamMaSua");

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("Shop.Infrastructure.KhachHang", b =>
                {
                    b.HasOne("Shop.Infrastructure.NguoiDung", "MaNdNavigation")
                        .WithMany("KhachHangs")
                        .HasForeignKey("MaNd")
                        .IsRequired()
                        .HasConstraintName("FK__KhachHang__MaND__3B75D760");

                    b.Navigation("MaNdNavigation");
                });

            modelBuilder.Entity("SanPhamSua", b =>
                {
                    b.Navigation("ChiTietDonHangs");

                    b.Navigation("DanhGia");

                    b.Navigation("GioHangs");

                    b.Navigation("HinhAnhSanPhams");
                });

            modelBuilder.Entity("Shop.Infrastructure.DonHang", b =>
                {
                    b.Navigation("ChiTietDonHangs");
                });

            modelBuilder.Entity("Shop.Infrastructure.KhachHang", b =>
                {
                    b.Navigation("DangKyTuVans");

                    b.Navigation("DonHangs");

                    b.Navigation("GioHangs");
                });

            modelBuilder.Entity("Shop.Infrastructure.LoaiSua", b =>
                {
                    b.Navigation("SanPhamSuas");
                });

            modelBuilder.Entity("Shop.Infrastructure.NguoiDung", b =>
                {
                    b.Navigation("DanhGia");

                    b.Navigation("KhachHangs");
                });
#pragma warning restore 612, 618
        }
    }
}
